[default.limits]
forms = "64 kB"
json = "1 MiB"
msgpack = "2 MiB"
"file/jpg" = "5 MiB"

[default]
key = "a default app-key"
extra = false
ident = "Rocket"

[debug]
address = "127.0.0.1"
port = 8001
workers = 1
keep_alive = 0
log_level = "normal"

[release]
address = "127.0.0.1"
port = 800
workers = 12
keep_alive = 5
log_level = "critical"