[default.limits]
forms = "64 kB"
json = "1 MiB"
msgpack = "2 MiB"
"file/jpg" = "5 MiB"

[default]
key = "a default app-key"
extra = false
ident = "Rocket"

[debug]
address = "0.0.0.0"
port = 8000
workers = 12
keep_alive = 12
log_level = "normal"

[release]
address = "0.0.0.0"
port = 8000
workers = 12
keep_alive = 12
log_level = "critical"

[default.tls]
certs = "examples/private/rsa_sha256_cert.pem"
key = "examples/private/rsa_sha256_key.pem"

[default.tls.mutual]
ca_certs = "examples/private/ca_cert.pem"
mandatory = true

